[build-system] 
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ollama-local-reviewer"
version = "1.0.1" 
description = "A local multi-agent code reviewer" 
dependencies = [ "pyyaml", "jinja2", "ollama" ]
readme = "README.md"

[project.scripts]
ollama-review = "src.driver:main"

[tool.setuptools]
packages = ["src", "prompts"]